#!/bin/bash

jupyter labextension install @jupyterlab/toc

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager
